### ISSUE TITLE
Define entities and models

### ISSUE THREAD

**Issue by rhannequin** [webdevesgi/website-api#1]
Here let's define what we're gonna manipulate. It is basically defining the features. We can work the API and the client at the same time if we create fake API calls from the client app while waiting for the API to be available.

**Comment by rhannequin** [comment]
Current features :
- events (CRUD)
- subscribers (to an event)
- talks (belong to an event)
- ideas (event suggestions)

**Comment by pgrimaud** [comment]
What do you think about another CRUD for members (a.k.a subscribers)?
We can do it easily with social network (Twitter, Facebook or Google).

Then, they will be able to subscribe to an event, talks about it, and submit ideas.

**Comment by rhannequin** [comment]
Handle members won't be that easy but indeed it could bring a better ux.

**Comment by tlenclos** [comment]
I don't think we need CRUD for members if we use social login & accounts.

**Comment by rhannequin** [comment]
We need at least to be able to create and update users, if the account's token is changed. I don't really know by now how to implement a website with only social login/accounts, do you guys have an idea how to do it?
Btw, I just read @thibzy 's answer so don't be surprised by my last commit (create User Model, duh).

**Comment by tlenclos** [comment]
There is a famous middleware that we could add to handle Facebook, Google and Twitter (at least) accounts. https://github.com/jaredhanson/passport
