### ISSUE TITLE
create User entity

### ISSUE THREAD

**Issue by jduval** [webdevesgi/website-api#11]
- basic login 
- social one (facebook / twitter / git?)

**Comment by rhannequin** [comment]
I'd like to use basic login. It's way too complicated for our needs to have a client app which uses an API, which itself uses an API (Github). If we manage users from Github API, we have to implement additional features like authorisation (allow our API to access to the user's Github account), token expiration, ...

We can easily create our own users management system in Ruby and it can be enough.

**Comment by jduval** [comment]
well in that case I'll start with basic login, and then see if we need social login.

**Comment by jduval** [comment]
basic stuff is done here.
