### ISSUE TITLE
API model

### ISSUE THREAD

**Issue by jduval** [webdevesgi/website-api#14]
Here is a schema of the API's data model:

```
Events
|_ Talks
|   |_ Speaker (user)
|_ Subscribers (users)

Ideas (subject which user wants to see as speaker or subscriber)
|_ From (user)
```

Something is missing? Feel free to fix it ;)

**Comment by rhannequin** [comment]
As it seems to be good, I close the issue. If we want to discuss about a change we can reopen it.
