### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by rhannequin** [webdevesgi/website-api#2]
Even if we are a few people and it is easy to give write permission to all of us as this is a Github organization, I think we should use the classical workflow which is using pull-requests.
It lets people see what everybody is doing, talk about code, make choices and not override other's code.
What do you think about this?

**Comment by rhannequin** [comment]
No need a validation workflow but it could be nice if everybody could comment on PR to notice others they saw the commits and agree to merge it. Stay tuned with Github's watch feature.

**Comment by tlenclos** [comment]
They'll have to learn english first. More seriously the pull requests workflow seems better and is the essence of github.

**Comment by rhannequin** [comment]
We can also -and it'd be better- use git's branches features, good occasion to master them and to organize better the features, what do you think?
